/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JeopardyHUDDailyDouble.java
 *
 * Created on Mar 19, 2011, 4:57:58 PM
 */

package jeopardygame;

/**
 *
 * @author Mac
 */
public class JeopardyHUDDailyDouble extends javax.swing.JPanel {

    /** Creates new form JeopardyHUDDailyDouble */
    public JeopardyHUDDailyDouble() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmptyBorderLabel = new javax.swing.JLabel();
        dailyDoubleLabel = new javax.swing.JLabel();
        dailyDoubleLabelShadow = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1200));
        setMinimumSize(new java.awt.Dimension(1920, 1200));
        setPreferredSize(new java.awt.Dimension(1920, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmptyBorderLabel.setBackground(new java.awt.Color(0, 0, 110));
        EmptyBorderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 60, true));
        add(EmptyBorderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1200));

        dailyDoubleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 228)); // NOI18N
        dailyDoubleLabel.setForeground(new java.awt.Color(255, 255, 255));
        dailyDoubleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dailyDoubleLabel.setText("DAILY DOUBLE");
        dailyDoubleLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 25, true));
        add(dailyDoubleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        dailyDoubleLabelShadow.setFont(new java.awt.Font("Lucida Grande", 1, 228)); // NOI18N
        dailyDoubleLabelShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dailyDoubleLabelShadow.setText("DAILY DOUBLE");
        dailyDoubleLabelShadow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 25, true));
        add(dailyDoubleLabelShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmptyBorderLabel;
    private javax.swing.JLabel dailyDoubleLabel;
    private javax.swing.JLabel dailyDoubleLabelShadow;
    // End of variables declaration//GEN-END:variables

}
