/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JeopardyCategory.java
 *
 * Created on Mar 19, 2011, 10:22:22 AM
 */

package jeopardygame;

/**
 *
 * @author Mac
 */
public class JeopardyCategory extends javax.swing.JPanel {

    /** Creates new form JeopardyCategory */
    public JeopardyCategory() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryForgroundLabel = new javax.swing.JLabel();
        CategoryBackgroundLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 150));
        setMaximumSize(new java.awt.Dimension(320, 200));
        setMinimumSize(new java.awt.Dimension(320, 200));
        setPreferredSize(new java.awt.Dimension(320, 200));
        setSize(new java.awt.Dimension(320, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoryForgroundLabel.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        CategoryForgroundLabel.setForeground(new java.awt.Color(255, 255, 255));
        CategoryForgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoryForgroundLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        add(CategoryForgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 200));
        CategoryForgroundLabel.getAccessibleContext().setAccessibleName("China, But");

        CategoryBackgroundLabel.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        CategoryBackgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(CategoryBackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 210));
    }// </editor-fold>//GEN-END:initComponents


    public void setText(String text)
    {
        CategoryBackgroundLabel.setText("<html><div align=\"center\">" + text.toUpperCase() + "</div></html>");
        CategoryForgroundLabel.setText("<html><div align=\"center\">" + text.toUpperCase() + "</div></html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryBackgroundLabel;
    private javax.swing.JLabel CategoryForgroundLabel;
    // End of variables declaration//GEN-END:variables

}
